/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP, lightColors } from "./settings/theme.js";

export default [
  Theme({
    name: "Kitty Dark",
    icon: "󰄛 ",
    "desktop.wallpaper.img": WP + "kittybl.jpeg",
  }),
  Theme({
    name: "Kitty Light",
    icon: "󰄛 ",
    "desktop.wallpaper.img": WP + "kitty.jpeg",
    ...lightColors,
    "theme.widget.bg": "$accent",
    "theme.widget.opacity": 64,
  }),
  Theme({
    name: "Leaves",
    icon: "󰌪 ",
    "desktop.wallpaper.img": WP + "leaves.jpg",
    "theme.accent.accent": "$green",
    "theme.accent.gradient": "to right, $accent, darken($accent, 14%)",
    "theme.widget.opacity": 92,
    "border.opacity": 86,
    "theme.bg": "transparentize(#171717, 0.3)",
    "bar.style": "floating",
    radii: 0,
  }),
  Theme({
    name: "Ivory",
    icon: "󰟆 ",
    ...lightColors,
    "desktop.wallpaper.img": WP + "ivory.png",
    "desktop.wallpaper.fg": "$bg_color",
    "desktop.screen_corners": false,
    "bar.style": "separated",
    "theme.widget.bg": "$accent",
    "theme.widget.opacity": 64,
    "desktop.drop_shadow": false,
    "border.width": 2,
    "border.opacity": 0,
    "theme.accent.gradient": "to right, $accent, darken($accent, 6%)",
    "hypr.inactive_border": "rgba(111111FF)",
    "bar.separators": false,
  }),
  Theme({
    name: "Space",
    icon: " ",
    "desktop.wallpaper.img": WP + "space.jpg",
    spacing: 11,
    padding: 10,
    radii: 12,
    "theme.accent.accent": "$magenta",
    "desktop.screen_corners": false,
    "desktop.clock.enable": false,
    "bar.separators": false,
    "bar.icon": "",
    "theme.bg": "transparentize(#171717, 0.3)",
    "theme.widget.opacity": 95,
    "bar.flat_buttons": false,
  }),
  Theme({
    name: "Tokyo",
    icon: " ",
    "desktop.wallpaper.img": WP + "tokyo.jpg",
    spacing: 4,
    padding: 10,
    radii: 8,
    popover_padding_multiplier: 1.4,
    "applauncher.height": 500,
    "applauncher.icon_size": 52,
    "applauncher.width": 500,
    "bar.icon": "",
    "bar.position": "top",
    "bar.separators": false,
    "bar.style": "normal",
    "battery.bar.full": true,
    "battery.bar.height": 14,
    "battery.bar.show_icon": true,
    "battery.bar.width": 70,
    "battery.low": 30,
    "battery.medium": 50,
    "border.color": "$fg-color",
    "border.opacity": 97,
    "border.width": 1,
    "color.blue": "#7aa2f7",
    "color.green": "#9ece6a",
    "color.magenta": "#ad8ee6",
    "color.orange": "#E79E64",
    "color.red": "#e05f65",
    "color.teal": "#449dab",
    "color.yellow": "#e0af68",
    "desktop.avatar": "/var/lib/AccountsService/icons/mhiri",
    "desktop.clock.enable": false,
    "desktop.clock.position": "center center",
    "desktop.dock.icon_size": 56,
    "desktop.drop_shadow": true,
    "desktop.screen_corners": true,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "desktop.wallpaper.fg": "#fff",
    "font.font": "RobotoMono Nerd Font",
    "font.mono": "RobotoMono Nerd Font",
    "font.size": 12,
    "hypr.inactive_border": "rgba(1a1b2600)",
    "hypr.wm_gaps_multiplier": 2.4,
    "theme.accent.accent": "$red",
    "theme.accent.fg": "#141414",
    "theme.accent.gradient": "to right, $accent, lighten($accent, 6%)",
    "theme.bg": "#1a1b26",
    "theme.fg": "#a9b1d6",
    "theme.scheme": "dark",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 95,
    "dashboard.sys_info_size": 70,
    "mpris.black_list": ["Caprine"],
    "mpris.preferred": "spotify",
    "notifications.black_list": ["Spotify"],
    "notifications.position": ["top", "right333333"],
    "notifications.width": 450,
    workspaces: 6,
  }),
];
